version: 2.1

jobs:
  build-and-bdd_test:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: |
            npm install
      - run:
          name: Run the assignment-testcase
          command: |
            pwd && ls -ll
            npx cypress run --spec "cypress/e2e/*/*.js" --headed --browser electron --env url="https://www.uat-driving.co.uk/"

workflows:
  version: 2
  test-assignment:
    jobs:
      - build-and-bdd_test
      
     
