version: 2.1

jobs:
  build-and-bdd_test:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: |
            npm install
      - run:
          name: Run the assignment-testcase
          command: |
            pwd && ls -ll
            npx cypress run --spec "cypress/e2e/Assignment-1/test-Scenario-7.cy.js" --headed --browser electron --env url="https://www.uat-driving.co.uk/"

  build-and-bdd_test-1:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: |
            npm install
      - run:
          name: Run the assignment-1-testcase
          command: |
            pwd && ls -ll
            npx cypress run --spec "cypress/e2e/Assignment-1/test-Scenario-5.cy.js" --headed --browser electron --env url="https://www.the-tls.co.uk/"
  
  build-and-bdd_test-2:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: |
            npm install
      - run:
          name: Run the assignment-2-testcase
          command: |
            pwd && ls -ll
            npx cypress run --spec "cypress/e2e/Assignment-1/test-Scenario-7.cy.js" --headed --browser electron --env url="https://www.the-tls.co.uk/"

  build-and-bdd_test-3:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: |
            npm install
      - run:
          name: Run the assignment-3-testcase
          command: |
            pwd && ls -ll
            npx cypress run --spec "cypress/e2e/Assignment-1/test-Scenario-8.cy.js" --headed --browser electron --env url="https://www.the-tls.co.uk/"

  build-and-bdd_test-4:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: |
            npm install
      - run:
          name: Run the practices
          command: |
            pwd && ls -ll
            npx cypress run --spec "cypress/e2e/practice-from-udemy-and-SDET/practices.cy.js" --headed --browser electron --env url="https://www.uat-driving.co.uk/"


workflows:
  version: 2
  test-assignment-666:
    jobs:
      - build-and-bdd_test
      - build-and-bdd_test-1
      - build-and-bdd_test-2
      - build-and-bdd_test-3
      - build-and-bdd_test-4
